import re

# https://github.com/bigscience-workshop/data_tooling/blob/6570774d81ea84912ff731d542f1abe39589ba3a/ac_dc/flagged_words.py
ENGLISH_FLAGGED_WORDS = [
    "anal",
    "bareback",
    "bbw",
    "bdsm",
    "blowjob",
    "blowjobs",
    "brazzers",
    "bukkake",
    "camgirl",
    "camwhore",
    "cocksucking",
    "cougar",
    "creampie",
    "cuckold",
    "cum",
    "cumming",
    "cums",
    "cumshot",
    "cumshots",
    "cumslut",
    "cunnilingus",
    "deepthroat",
    "deepthroating",
    "dildo",
    "dildos",
    "dogging",
    "doggystyle",
    "dominatrix",
    "erotic",
    "fellatio",
    "femdom",
    "fingering",
    "fisting",
    "footjob",
    "gangbang",
    "handjob",
    "hentai",
    "horney",
    "horniest",
    "horny",
    "jism",
    "jizz",
    "masterbating",
    "masturbate",
    "masturbating",
    "masturbation",
    "milf",
    "orgies",
    "orgy",
    "pegging",
    "porn",
    "pornhub",
    "porno",
    "pornos",
    "pornstar",
    "pornstars",
    "redtube",
    "rimming",
    "slutty",
    "squirting",
    "strapon",
    "threesome",
    "vibrator",
    "xhamster",
    "xnxx",
    "xvideos",
    "xxx",
    "youporn",
]

SPANISH_FLAGGED_WORDS = ENGLISH_FLAGGED_WORDS \
    + [
        "chupar el coño",
        "chupar la concha",
        "chupar la polla",
        "chupar la verga",
        "comer el coño",
        "comer la concha",
        "comer la polla",
        "comer la verga",
        "coprofagía",
        "correrse",
        "cunillingus",
        "fagging",
        "felación",
        "felching",
        "follada",
        "follador de culo",
        "folladores",
        "fudge packer",
        "hacer una paja",
        "hacerse una paja",
        "hore",
        "kock",
        "macizorra",
        "madre folladora",
        "mamada",
        "perro follador",
        "pisser",
        "pornografía",
        "sado",
        "sadomasoquismo",
        "sadomasoquista",
        "sexo anal",
        "skank",
        "smegma",
        "x clasificado",
        " foll",
        "polla",
        "coño",
        "verga",
        "concha",
        "paja",
        "culo",
        "joder",
        "mierda",
        " mea",
        " caga",
        "me corr",
        "te corr",
        "se corr",
        " chup",
        "cabrón",
        "gilipollez",
        "comersela",
        " put",
        "cojon",
        "perra de tu madre",
        "perra de su madre"
    ]

TEXT_LENGTH_PATTERN = re.compile(r"^(#\d+\s*)?$")

ANONYMIZE_URL_MAIL = re.compile(r"#\d+|<URL>|<MAIL>")
